### ISSUE TITLE
Support desktop file creation

### ISSUE THREAD

**Issue by tinywrkb** [flathub/com.google.Chrome#16]
It would be nice to be able to generate desktop files for web apps.

If we put aside security concerns (if any) and having the user manually append `~/.var/app/APP-ID/data` to `XDG_DATA_DIR` for the host, these are the requirements:

* Add desktop-file-utils.
* From xdg-utils add xdg-desktop-icon, xdg-desktop-menu, and xdg-icon-resource. We want to patch xdg-desktop-menu so the generated Exec value will use `flatpak run` and take into account `FLATPAK_ID`.

I thought I'll give this a look the other day but I'll probably get to it much later so I'm at least reporting this.

**Comment by tinywrkb** [comment]
Closing, Flextop is working perfectly.

**Comment by refi64** [comment]
Dang how did you find it so quickly :sweat_smile: completely forgot this issue was open, but yeah flextop is the current "hack" to make this work, will add it into Chrome shortly. (Main reason I'm not atm is that it partly depends on a zypak change for the new windows to actually be able to see shared Chrome instances properly.)

**Comment by tinywrkb** [comment]
It was listed in Github's activity and Flatpak Chrome is my main web browser for quite a while now so I was thrilled to test this.
