### ISSUE TITLE
Long delay before launch on Wayland

### ISSUE THREAD

**Issue by stuarthayhurst** [flathub/com.google.Chrome#308]
The flatpak has a long delay before it actually launches when launched graphically (GNOME's app display), but launching with `flatpak run com.google.Chrome` launches it instantly. Happens with AMD or NVIDIA graphics.

Version: 125.0.6422.141-1
Flatpak version: 1.14.8
Debian Sid / Experimental, GNOME 46.

**Comment by stuarthayhurst** [comment]
It took 2 minutes and 10 seconds to launch graphically, but via the terminal is near-instant.

**Comment by charlesthobe** [comment]
Same here happens with flatpak firefox and chrome but only when launching a secondary option like InPrivare/Incognito or the Profile manager (firefox launch option)

This behavior has been for about a week and I suspect it is a bug in flatpak or gnome rather than the packages.

Chrome package version: 126.0.6478.114-1
Flatpak version 1.14.8
Debian Trixie/Testing, GNOME 46

**Comment by stuarthayhurst** [comment]
It seems to be fixed with flatpak 1.15.8 from Debian experimental, I'll close this if it fixes it for you too @charlesthobe

**Comment by charlesthobe** [comment]
Alright I have installed `flatpak_1.15.8-1_amd64.deb` from the experimental repository and now it works fine, thanks for the info :)
